server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

spring:
  data:
    mongodb:
      username: "{cipher}AQAt1YhudNieGERV5Fzb2EtnF5FE2NAU22SYANnqCLkL1YTv8WUNqo9Aq468CH00uXAUm4Q6XRT+YyeIVQtJL0UXMSOLPpQPZQkJrbi9nhPNcRsVG786K2HwLgBKIabJ+J2C26gAJmNhGeDIfnwusm1y9i9xTsQk/5jZP/PN4uRyh8yn1rFGImMeXL80CfH509JCsqFK7vkXVAq4ZKdu5Fq6bHiwF0xbLyZqklDCegwzxiMtOlX+fcF8QZEJgnVfhJt3DRMRnsSzvOMZ1ECkAmHG2i1X9AIM1VJmezz89+CMcgG4l3PjNROmxhGYjnfYAOBMBh7w21F0S4Qmjz6WXM7VxW9h9IMd+yOn/rtJFWzOP/5hk0bIZSYQ+W9z0RbbOco="
      password: "{cipher}AQA45BEa7iQwb2oo+qmieQZvQFLDfnWXDemUVgkYLzljWWaDzM4Q6mbCqOS/TuooqvH6R/6tJlYwPdKIBatXLWY4Z+zP7ZtLSpPPGZbnemm7wvN2PNzOqvWYGgN2dX6GSx+OtctGo+RC5GrUflPdt51cBqx5USCQr6SJOSeti80qum9daLCMsnF5NugUMLO0W1Hg1oYLu7PQmBZAXE+U43nybZsdv3VUTPWUQuY4191+dGTCNSyU+GcMJNwD61r35aLRjZfTFkGtvUtHsn/7OxYjdpMH65J5rOO4PM1t6Lac4qxIkHVQTOwS8gJsj1hlHyYRPHXoJcL7SZgZIxrevr3Q8n6oqVk8N4MUDoiXf1HBb4Fbni2ADdGgmJJN/RuaK/M="
      host: mongo
      port: 27017
      database: Profile
  cloud:
    config:
      uri: http://config-server:8888
